### ISSUE TITLE
Add support for cuelang based configs

### ISSUE THREAD

**Issue by manugarg** [cloudprober/cloudprober#178]
Cloudprober configs are currently based on protocol buffers and Go text templates. Cloudprober first parses the config files as Go templates and then as text protos (aka textproto). This is not a widely used format for configs in the industry. This limits the adoption of Cloudprober. Also, current configs don't support including other configs, for example, for company wide common options.

We should improve on this situation. I think Cue lang may provide a way.

### Requirements
* Current configs should continue to work.
* Cloudprober should support YAML configs at a minimum.
* Cloudprober should support importing config templates (other configs), to avoid duplication. This will of course not work with textproto based configs, but it may work with cuelang based configs.

### Proposal
Explore using Cue lang for configs. We could use Cue data definitions (schema) to define config options, instead of protocol buffers (.proto files). Cue seems to support converting textprotos to Cue: https://pkg.go.dev/cuelang.org/go@v0.4.3/encoding/protobuf/textproto -- this should allow us to continue to support existing configs.

### Plan
1. Generate Cue schema from existing .proto files, using this: https://pkg.go.dev/cuelang.org/go/encoding/protobuf
2. Add support for taking in Cue lang configs, and converting them into Go data structures: https://pkg.go.dev/cuelang.org/go@v0.4.3/encoding/gocode/gocodec#Codec.Encode.
3. Add support for converting textprotos to Cue values, and Cue values to Go data structures. This is to continue supporting existing configs.
4. Create a bridge between Cloudprober and config options that is independent of the underlying config language.
    a. Cloudprober code, internally, should use Go data structures for configs, instead of dealing with and using protobufs directly.
    b. We should implement a layer to convert protobufs to these Go types.
    c. These Go types will be what Cue values will be converted into.

We could do the step 4 first and use Go types to generate the Cue schema, but this schema should support existing config files also. Generating schema from protobufs will enforce that, though I am not sure how reliable this code generation is today.

This will be a long process with a lot of figuring out as we go.

**Comment by manugarg** [comment]
Look at this code for how to generate Cue schema from .proto files:
https://github.com/fourierr/cue-0.2.2-fix/blob/main/encoding/protobuf/protobuf_test.go

Example input with a bunch of imports:
https://github.com/fourierr/cue-0.2.2-fix/blob/main/encoding/protobuf/testdata/istio.io/api/mixer/v1/mixer.proto
Output:
https://github.com/fourierr/cue-0.2.2-fix/blob/main/encoding/protobuf/testdata/istio.io/api/mixer/v1/mixer_proto_gen.cue

Imports are part of the same package though. I've to see how it works across package boundaries.

**Comment by manugarg** [comment]
Experimentation so far:

I tried generating Cue schema from protobufs. Steps:

```
# Set up code in a temp dir:
PROJECT=github.com/cloudprober/cloudprober
TMPDIR=$(mktemp -d); mkdir -p ${TMPDIR}/github.com/cloudprober; cp -a ../cloudprober $TMPDIR/github.com/cloudprober
cd $TMPDIR

mkdir $PROJECT/cue.mod
echo "module: \"$PROJECT\"" > $PROJECT/cue.mod/module.cue
```

Import proto into CUE:
```
cue import proto -I . $PROJECT/config/proto/config.proto --proto_enum json -f
```

Create a yaml for testing:
```
cat <<EOF > /tmp/cloudprober.yaml
probe:
  - name: "some"
    type: PING
    targets:
      hostNames: "test"
    sourceIp: "0.0.0.0"
    pingProbe: {}

  - name: "some2"
    type: HTTP
    targets:
      hostNames: "test"
    sourceIp: "0.0.0.0"
    httpProbe: {}
EOF
```

Validate and eval:
```
cd $TMPDIR/$PROJECT
cue vet /tmp/cloudprober.yaml config/proto/config_proto_gen.cue -d '#ProberConfig'
cue eval /tmp/cloudprober.yaml config/proto/config_proto_gen.cue -d '#ProberConfig' -c
probe: [{
    name: "some"
    type: "PING"
    targets: {
        hostNames: "test"
    }
    sourceIp: "0.0.0.0"
    pingProbe: {}
}, {
    name: "some2"
    type: "HTTP"
    targets: {
        hostNames: "test"
    }
    sourceIp: "0.0.0.0"
    httpProbe: {}
}]
```

**Comment by manugarg** [comment]
Based on the above findings, if we generate CUE schema from proto files, we can write config files in YAML today itself. I think this is great news. I am not sure how robust this will be, but it's encouraging.

**Comment by manugarg** [comment]
https://github.com/cloudprober/cloudprober/pull/181/files shows CUE schema and code to generate CUE schema from proto files.

**Comment by manugarg** [comment]
> One problem I see right now is that `cue` tool takes a while to eval the yaml file. I hope it will be faster if we load CUE schema in advance, and then eval. I'll do some testing.

Verified with the code[1] that it's loading the schema that takes time (~2.5s). Likely due to the fact that our schema is spread over 40+ files. We don't really want to slow down Cloudprober startup, but this maybe okay for now. We'll only build schema if YAML file is provided.

[1] Code looks like this:
```
       bis := load.Instances([]string{"config/proto/config_proto_gen.cue"}, nil)
       r := cuecontext.New()
       s := r.BuildInstance(bis[0])
       if s.Err() != nil {
		log.Fatal(s.Err())
	}

	proberConfigDef := s.LookupDef("#ProberConfig")
	if proberConfigDef.Err() != nil {
		log.Fatal(proberConfigDef.Err())
	}

	expr, err := cueyaml.Unmarshal([]byte(testYAML))
	if err != nil {
		log.Fatal(err)
	}

	v := proberConfigDef.Context().BuildExpr(expr)
	if v.Err() != nil {
		log.Fatal(v.Err())
	}
	fmt.Println(v)
```

**Comment by manugarg** [comment]
I've been experimenting a bit more and found another issue.

By the above method, enums end up showing as strings in the generated textproto (see the type field [here](https://github.com/cloudprober/cloudprober/issues/178#issuecomment-1238983045)), i.e. because neither YAML nor CUE have the concept of enums.

I think that's because when CUE converts CUE values to textproto, it doesn't look at protobufs at all. It's working entirely off of the CUE Schema and CUE schema doesn't seem to capture if a certain field was an enum in protobuf (it sort of does though ([example](https://github.com/cloudprober/cloudprober/blob/d570c973d2/probes/proto/config_proto_gen.cue#L21-L54), but it doesn't make use of it, AFAICT).

**Comment by manugarg** [comment]
Some improvisation: #189. In this change we replace enum fields in the following manner: `ip_type: "PUBLIC"` will get replaced by `ip_type: PUBLIC` in the generated textproto. With this change, Cloudprober will happily take the config like the following:

```
probe:
  - name: "some"
    type: PING
    targets:
      host_names: "test"
    source_ip: "0.0.0.0"

  - name: "some2"
    type: HTTP
    targets:
      host_names: "nummus.robinhood.com"
    timeout: "5s"
    interval: "30s"
    source_ip: "0.0.0.0"
    http_probe:
      protocol: HTTPS
      relative_url: "/currency_pairs/"
    validator:
      - name: "status_code_2xx"
        http_validator:
          success_status_codes: "200-299"
      - name: "currencies"
        regex: ".*BTC.*ETH.*DOGE.*SHIB.*"
```
