### ISSUE TITLE
Quick configuration of multiple HTTP targets

### ISSUE THREAD

**Issue by manugarg** [cloudprober/cloudprober#609]
We recently encountered a use case we needed to monitor multiple, but kind of related, URLs. This resulted in multiple probes which could be just one probe. This made me think: we should allow target labels to configure HTTP probe even more, without targets definition itself becoming too complicated. I am thinking of something like the following:

```
targets:
  endpoints:
   - name: "frontend1"
      url: "https://frontend-1-host/url1"
   - name: "frontend2"
      url: "https://frontend-2-host/url2"
```

- [x] Modify HTTP probe to support internal Cloudprober labels. Done: #607.
- [x] Add support for the scheme label.
- [x] Add new targets type which can be directly defined within the targets config. These target types will take: Name, IP, Port, Labels, URL. #606.
