### ISSUE TITLE
[probes.dns] `latency_distribution` doesn't work DNS probe

### ISSUE THREAD

**Issue by manugarg** [cloudprober/cloudprober#835]
### Discussed in https://github.com/cloudprober/cloudprober/discussions/833

<div type='discussions-op-text'>

<sup>Originally posted by **therealak12** August 25, 2024</sup>
Hi, I have a simple yaml config as follows:

```yaml
probe:
    - name: "google"
      type: DNS
      targets:
        host_names: "8.8.8.8"
      dns_probe:
        queryType: A
        resolved_domain: "google.com"
      latency_distribution:
        explicit_buckets: "0.001,0.005,0.01,0.02,0.03,0.05,0.075,0.1,0.2,0.5,0.75,1,1.5,2,2.5,3,4,5"
      interval: 1s
      timeout: 1s
      latency_unit: s
```

The issue is that only the last probe is recorded for the histogram metric. The `/metrics` endpoint always returns a response like this (count doesn't exceed 1):

```
latency_count{probe="ext-google",dst="8.8.8.8"} 1 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="0.001"} 0 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="0.005"} 0 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="0.01"} 0 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="0.02"} 0 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="0.03"} 0 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="0.05"} 1 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="0.075"} 1 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="0.1"} 1 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="0.2"} 1 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="0.5"} 1 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="0.75"} 1 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="1"} 1 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="1.5"} 1 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="2"} 1 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="2.5"} 1 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="3"} 1 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="4"} 1 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="5"} 1 1724571103875
latency_bucket{probe="ext-google",dst="8.8.8.8",le="+Inf"} 1 1724571103875
```

---

My question: Is this behavior intentional or can it be considered a bug?

[This line](https://github.com/cloudprober/cloudprober/blob/cae2148899a6af6a7ea5322e32812fafa3f6e313/probes/dns/dns.go#L268) is likely causing the behavior. It should be put in the `Start` method or should be changed like this:
```golang
if result.latency == nil {
    result.latency = p.opts.LatencyDist.CloneDist()
}
```</div>
